USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/xolo/era4g/BoardConfigVendor.mk

TARGET_OTA_ASSERT_DEVICE := era_4G,era4g,era4G,sc9830

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_BOARD_PLATFORM := sc8830
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_GLOBAL_CFLAGS += -mfloat-abi=softfp -mfpu=neon-vfpv4 -mtune=cortex-a7
TARGET_GLOBAL_CPPFLAGS += -mfloat-abi=softfp -mfpu=neon-vfpv4 -mtune=cortex-a7
TARGET_CPU_SMP := true
BOARD_VENDOR := xolo
TARGET_SPECIFIC_HEADER_PATH := device/xolo/era4g/include

ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOOTLOADER_BOARD_NAME := sc8830

# Kernel
TARGET_KERNEL_ARCH                           := arm
TARGET_PREBUILT_KERNEL                       := device/xolo/era4g/kernel
BOARD_KERNEL_CMDLINE                         := console=ttyS1,115200n8 androidboot.selinux=permissive
BOARD_KERNEL_BASE                            := 0x00000000
BOARD_KERNEL_PAGESIZE                        := 2048
BOARD_KERNEL_IMAGE_NAME                      := Image
BOARD_MKBOOTIMG_ARGS                         := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --dt device/xolo/era4g/dt.img

# Audio
SOC_SCX30G_V2 := true
BOARD_USES_TINYALSA_AUDIO := true
BOARD_USES_SS_VOIP := true
BOARD_USE_LIBATCHANNEL_WRAPPER := true
BOARD_HAVE_FM_BCM := true

ADDITIONAL_DEFAULT_PROPERTIES += ro.secure=0 \
ro.debuggable=1 \
ro.adb.secure=0 \
persist.sys.usb.config=adb \
ro.adb.secure=0

# something
BOARD_NEEDS_MEMORYHEAPION_SPRD := true
COMMON_GLOBAL_CFLAGS += -DSPRD_HARDWARE


TARGET_USERIMAGES_USE_EXT4 := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1932734976
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5495377408
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_FLASH_BLOCK_SIZE := 131072
USE_OPENGL_RENDERER := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true
COMMON_GLOBAL_CFLAGS += -DFORCE_SCREENSHOT_CPU_PATH
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3

TARGET_BOARD_INFO_FILE := device/xolo/era4g/board-info.txt
BOARD_EGL_CFG := device/xolo/era4g/egl.cfg

# Resolution
TARGET_SCREEN_WIDTH := 720
TARGET_SCREEN_HEIGHT := 1280

USE_SPRD_HWCOMPOSER := true
USE_OPENGL_RENDERER := true
BOARD_USE_MHEAP_SCREENSHOT := true
TARGET_BOARD_PLATFORM_GPU := ARM Mali-400
USE_OVERLAY_COMPOSER_GPU := true
USE_SPRD_DITHER := true
DEVICE_FORCE_VIDEO_GO_OVERLAYCOMPOSER := true
BOARD_EGL_WORKAROUND_BUG_10194508 := true
# HWUI_COMPILE_FOR_PERF := true
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true
COMMON_GLOBAL_CFLAGS += -DSC8830_HWC
BOARD_CANT_REALLOCATE_OMX_BUFFERS := true

BOARD_RIL_CLASS := ../../../device/xolo/era4g/ril

# bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_SPRD := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/xolo/era4g/bluetooth
BOARD_BLUEDROID_VENDOR_CONF := device/xolo/era4g/bluetooth/libbt_vndcfg.txt

# Wifi
WIFI_DRIVER_MODULE_PATH := /lib/modules/sprdwl.ko
WIFI_DRIVER_FW_PATH_PARAM := /data/misc/wifi/fwpath
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WIFI_DRIVER_MODULE_NAME := sprdwl
BOARD_WLAN_DEVICE := qcwcn
BOARD_WLAN_DEVICE_REV := MARLIN_15C_SS_W16.09.3
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_PRIVATE_LIB := lib_driver_cmd_qcwcn
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_qcwcn
WIFI_BAND := 802_11_ABG

# Charger
BOARD_CHARGER_ENABLE_SUSPEND := true
BOARD_CHARGING_MODE_BOOTING_LPM := /sys/class/power_supply/battery/batt_lp_charging

# sepolicy
BOARD_SEPOLICY_DIRS += device/xolo/era4g/sepolicy

# Camera
CAMERA_SUPPORT_SIZE := 5M
#android zsl capture
TARGET_BOARD_CAMERA_ANDROID_ZSL_MODE := false
#back camera rotation capture
TARGET_BOARD_BACK_CAMERA_ROTATION := false
#front camera rotation capture
TARGET_BOARD_FRONT_CAMERA_ROTATION := false
#rotation capture
TARGET_BOARD_CAMERA_ROTATION_CAPTURE := false
TARGET_BOARD_CAMERA_HAL_VERSION := 1.0
TARGET_BOARD_CAMERA_ANTI_FLICKER := true
TARGET_BOARD_USE_THRID_LIB := true
TARGET_BOARD_USE_THIRD_AF_LIB_A := true
TARGET_BOARD_USE_ALC_AE_AWB := true


TARGET_HAS_BACKLIT_KEYS := false

TARGET_RECOVERY_FSTAB = device/xolo/era4g/recovery.fstab
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
RECOVERY_GRAPHICS_USE_LINELENGTH := true
BOARD_HAS_NO_SELECT_BUTTON := true
